# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty
warnings_are_errors: false

addons:
  sources:
  - ubuntu-toolchain-r-test
  apt:
    packages:
    - libgpgme11-dev
    - unixodbc
    - unixodbc-dev
    - tdsodbc
    - libsqliteodbc

before_script:
  gpg --import ./inst/axthelm-pub-asc.gpg
 
after_success:
  - Rscript -e 'covr::codecov()'
